sudo: false
dist: trusty
language: rust
rust:
- nightly

addons:
  apt:
    packages:
      - libarchive-dev
      # necessary for `travis-cargo coveralls --no-sudo`
      # also for zmq from source, due to zmq_has dependency build error
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - make
      - automake
      - gcc
      - build-essential
      - g++
      - cpp
      - libc6-dev
      - man-db
      - autoconf
      - pkg-config
      - libtool
      - git
      # optional: only required for the --verify flag of coveralls
      - binutils-dev

  postgresql: "9.5"

services:
    - postgresql

before_script:
  - psql --version
  - psql -c 'create database cortex_tester;' -U postgres
  - psql -c "create user cortex_tester with password 'cortex_tester';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE cortex_tester TO cortex_tester;' -U postgres
  - export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
# load travis-cargo
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
  - |
      git clone --depth 1 -b stable https://github.com/jedisct1/libsodium.git
      cd libsodium
      ./autogen.sh
      ./configure --prefix=$HOME
      make
      make install
      cd ..
      wget https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.tar.gz
      tar zxf zeromq-3.2.5.tar.gz
      cd zeromq-3.2.5
      ./autogen.sh
      ./configure --prefix=$HOME --with-libsodium
      make
      make install
      cd ..


after_success:
  # upload the documentation from the build with nightly (automatically only actually
  # runs on the master branch, not individual PRs)
  - "./scripts/doc-upload.sh"
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - travis-cargo coveralls --no-sudo --verify

env:
  global:
    # for zmq
    - PATH=$HOME/.local/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/lib
    - PKG_CONFIG_PATH=$HOME/lib/pkgconfig
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    # encrypted github token for doc upload
    - secure: xUGnnfKOeDrV1jxamRV3aH1z8VqYNe6BVxVAUZCC5XjR/6b3UCL+4dQ2cWo7JWAO43OuEA5KD7GVGjheXwxiIo2kujKvzsInJoCbNEIkFwN3pCKi+QU0vI+Q3k8OGx20vS7dFlrdzaCpwrsXq8TJWojL77xN3XgJyv34Eu/DFc8CzQqcGybpoG88prXjmXQWuyckqEpGPvlM5zxxP7TFlx9jHf+ng+p4BZbJDSNyHlntGS2Mn4f2c5ENmVO/EogW1Ox9UIuFJYr/rSgSymmURTVUmudt5iWaYU6bZs9DpIuD/0ZSL/0tKsyQhmnJNM7JZ7NRg/8zosQRVz/5x+JbClw7CLuZG0mnCMx5pFVGAcTtNIFlYTA0i2k3kjOlt339IOdQWAflUnb/Uj39XKOtzi2J7fMhS+BkKdLwsIf4g97JKcxrxX4595dpcuUCmFvnDfxORnqaE/5xGn4QPb1lfk1NlaYMBhS5nnL4fw+NmhS/eOddXJDh7hO9QOgR/qPvxttU/JlGxZmzpr6vJESd9l+RjfnO8HMMbJ5Y2YMjdZ6uuVY1qhOVXX1eP4QqQf9B8kbvnf9WC856DZTdNq0CeXX3ISfEgmO+ts1R6Py9IWf0cimFzrMesxMB/xECg7kFQOdLYZg6GnFEM3MXB2Dsy+IeWrofE/0fyq8PLfDO2/Y=
