language: rust
rust: nightly

before_script:
  - psql -c 'create database cortex_tester;' -U postgres
  - psql -c "create user cortex_tester with password 'cortex_tester';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE cortex_tester TO cortex_tester;' -U postgres