language: rust
rust: nightly
sudo: false
addons:
  apt:
    packages:
      - libarchive-dev
      - libzmq3-dev
      # necessary for `travis-cargo coveralls --no-sudo`
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

before_script:
  - psql -c 'create database cortex_tester;' -U postgres
  - psql -c "create user cortex_tester with password 'cortex_tester';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE cortex_tester TO cortex_tester;' -U postgres
# load travis-cargo
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
  - travis-cargo doc
after_success:
  # upload the documentation (automatically only actually runs on the master branch, not individual PRs)
  - travis-cargo doc-upload
  - travis-cargo coveralls --no-sudo

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    # encrypted github token for doc upload
    - secure: WluBxaY8rxaM3M9D8+1h5dnuduUDgOXKmLmAxQeIld8x2XSiJzVPk0/wUUQHVrJ+ntMS8hswcBJbkStS/pyabcVfqvrIxmdDZxcw+CwI3RTELFv/ukidmP8AEzr90HJ9/O00gdHgiVgWxfWXip64yXzKtWR4nhvcmfZaA3d4Nl+RSQbmCh5vS8uj+DrydeYRrDPwNz3MneYhnEH6gbap9f9n1Kyc6v4GnnmEy1onwI+8ZXK1bEmtUhWLVgV0ymrMhPdgFwtTN5Ah7iIOguZTbWkns5Nz+YWSQUPjgN+m6TjGgOs2xyv5iTlXS0LiMcKoihwlrQulEf/JE9rw1Yq/q/AFsdONX33c9Fv0fizd/vQQYmI17aDU6IwstnaTNYM2nlDia+KSl64ZVzNG3tlwPVaDabRZO8qDbPLRYSruUq0PeDJ344BKlGxh1Gp+nZOxb1LF/o4iPhfv6z5gskNg/1zQtdu5+XBCM+KuXDjf/sRUkGxbtOJ/dxS1Zmtql5Rh9ICeA4E0QMD0xFWiDf7fbC3mVMmeObRZoXXibRSvPZ54GCDEQIBanIGaMXuHZSaDcAZvY/NILQXT88QVxfbXVBuDTj5Usmn9IO/1sRriyUgrVH/+wfkx43pkxi2qEPkZRdpCIoNILtFYU1Eu6Y6kiJhtO/NGYqTyNW53andFyuw=
